experiment_name: read_mapping

input: 
  sample table: inputs/samples.tsv
  adapter_file: inputs/all_illumina_adapters.fa  
  reference genome: inputs/ref_genome/ref_genome.fasta

scratch directory: scratch
results directory: results